#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [1]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [2]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[209 295 291 212 195 108 168 329 444 276]
 [141 255 212 496 338 497 278 292 450 281]
 [121 239 368 379 184 210 155 465 409 403]
 [169 231 423 258 365 166 304 422 284 394]
 [124 130 102 433 292 376 220 411 427 296]
 [477 217 367 346 190 209 221 474 166 361]
 [340 370 174 458 455 279 292 270 460 277]
 [454 323 441 101 185 315 326 153 241 379]
 [301 435 374 172 231 232 170 242 262 293]
 [344 160 208 424 262 203 147 498 192 461]]


0    1    2    3    4    5    6    7    8    9
0  209  295  291  212  195  108  168  329  444  276
1  141  255  212  496  338  497  278  292  450  281
2  121  239  368  379  184  210  155  465  409  403
3  169  231  423  258  365  166  304  422  284  394
4  124  130  102  433  292  376  220  411  427  296
5  477  217  367  346  190  209  221  474  166  361
6  340  370  174  458  455  279  292  270  460  277
7  454  323  441  101  185  315  326  153  241  379
8  301  435  374  172  231  232  170  242  262  293
9  344  160  208  424  262  203  147  498  192  461

In [4]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.69987246 0.14601537 0.41263342]
 [0.96210778 0.84837064 0.3527017 ]
 [0.42045751 0.08280921 0.02900134]
 [0.08512712 0.85766569 0.3914273 ]
 [0.12015083 0.03394384 0.44898927]]


колонка 1  колонка 2  колонка 3
0   0.699872   0.146015   0.412633
1   0.962108   0.848371   0.352702
2   0.420458   0.082809   0.029001
3   0.085127   0.857666   0.391427
4   0.120151   0.033944   0.448989

In [5]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {"Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
pd.DataFrame(d, index=[10,20,30,40,50])

Петя      Вася    Микола
10  0.791371  0.660549  0.238225
20  0.842110  0.136313  0.680777
30  0.450704  0.271982  0.856346
40  0.777184  0.349789  0.810908
50  0.891317  0.447674  0.101926

In [6]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [7]:
str(name_rik[0])

"('Вася', 2001)"

In [8]:
!echo "Вася, 2001\nПетя, 2000,\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

'cat' is not recognized as an internal or external command,
operable program or batch file.


ParserError: Too many columns specified: expected 2 and found 1

### ЗАВДАННЯ

In [11]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame([0,1,2,3,4,5,6,7,8,9])
print(df1_1)

   0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9


In [12]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 чисел з плаваючою точкою
df1_2 = np.random.random((5,6))
print(df1_2)

[[0.39360822 0.59882267 0.4161298  0.70112444 0.30839871 0.63886576]
 [0.52905939 0.26850414 0.37320934 0.40550541 0.15500131 0.81488741]
 [0.77148905 0.5559368  0.63566837 0.7057322  0.05592589 0.25412438]
 [0.16269426 0.68180212 0.85102662 0.68753665 0.46056842 0.5878601 ]
 [0.36541694 0.98763478 0.18581465 0.54545669 0.43911294 0.76931404]]


ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [13]:
df1_3 = pd.DataFrame({'name': ['Петро', 'Іван', 'Степан'], 'SecondName': ['Петров','Іванов','Степанов'],'BirthDate':['2000','2002','2001'],'MobileNumber':['222-222-2222','333-333-3333','444-444-4444']})
print(df1_3)

     name SecondName BirthDate  MobileNumber
0   Петро     Петров      2000  222-222-2222
1    Іван     Іванов      2002  333-333-3333
2  Степан   Степанов      2001  444-444-4444


In [14]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls
df1_4 = df = pd.read_csv("https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls")
print(df1_4[:20])

HTTPError: HTTP Error 404: Not Found

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [15]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [16]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [17]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [18]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [19]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [20]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [21]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [22]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [23]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [24]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [25]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [26]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [27]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [30]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [35]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
print(titanic['Age'].describe())
print(titanic['Fare'].describe())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64
count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64


In [40]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
print(titanic.shape)

(891, 12)


In [51]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
cond = titanic['Survived']==1
titanic[cond].shape

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [ ]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

In [ ]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

In [ ]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

In [ ]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

In [ ]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

In [ ]:
df

In [ ]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

In [ ]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

In [ ]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

In [ ]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

In [ ]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

In [ ]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

In [ ]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

In [ ]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

In [ ]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

### ЗАВДАННЯ

In [46]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [47]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df["рік завершення школи"] = ["2018", "2020", "200"]
df


ім'я  вік рейтинг рік завершення школи
0  Петя   22      10                 2018
1  Вася  200       3                 2020
2  Галя   21       2                  200

In [48]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.loc[2, "рік завершення школи"] = 2020
df


ім'я  вік рейтинг рік завершення школи
0  Петя   22      10                 2018
1  Вася  200       3                 2020
2  Галя   21       2                 2020

In [49]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [52]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [62]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
kol_pass = titanic.query('20< Age < 30 & Pclass == 2 & Sex == male')
kol_pass

UndefinedVariableError: name 'male' is not defined

In [63]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = titanic.fillna({"Fare": "***"}, inplace=True)
df

In [64]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
cond = titanic['Pclass'] == 1
avg_price = titanic[cond].groupby(["Pclass"])
print(avg_price["Fare"].mean())

Pclass
1    84.154687
Name: Fare, dtype: float64


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [ ]:
titanic.head(3)

In [ ]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

In [ ]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

In [ ]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

### ЗАВДАННЯ

In [66]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
malecond = titanic['Sex'] == 'male'
femalecond = titanic['Sex'] == 'female'

max_ageMale = titanic[malecond]['Age'].max()
max_geFaemale = titanic[femalecond]['Age'].max()
print('male =',max_ageMale)
print('female =',max_ageFemale)

male = 80.0
female = 63.0


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [ ]:
surv_table = ...
surv_table